# Generated by Django 5.1.1 on 2024-11-20 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_movielist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='lenght',
            new_name='length',
        ),
    ]
